### ISSUE TITLE
FileNotFoundError When Trying to Load Model Checkpoint

### ISSUE THREAD

**Issue by showf68** [REYD-TTS/yiddish-tts-texts#7]
### Description
I encountered a `FileNotFoundError` when trying to run the `synthesize.py` script using the provided Dockerfile. The error message indicates that the file `./output/ckpt/yivo_respelled/100000.pth.tar` is not found.

### Steps to Reproduce
1. Build the Docker image using the provided Dockerfile.
2. Run the Docker container with the necessary command-line arguments.
3. Execute the command inside the image:
`python synthesize.py --text "איך בין א ייד" --speaker_id 1 --restore_step 100000 --mode single -p config/yivo_respelled/preprocess.yaml -m config/yivo_respelled/model.yaml -t config/yivo_respelled/train.yaml`

### Error Message
```
Traceback (most recent call last):
File "synthesize.py", line 223, in <module>
model = get_model(args, configs, device, train=False)
File "/FastSpeech2/utils/model.py", line 20, in get_model
ckpt = torch.load(ckpt_path)
File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
with _open_file_like(f, 'rb') as opened_file:
File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
return _open_file(name_or_buffer, mode)
File "/usr/local/lib/python3.8/site-packages/torch/serialization.py", line 252, in init
super().init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './output/ckpt/yivo_respelled/100000.pth.tar'
```

Thank you for your assistance!

### DockerFile:

```
FROM python:3.8

RUN git clone https://github.com/REYD-TTS/FastSpeech2.git && \
    cd FastSpeech2 && \
    git checkout colab

WORKDIR FastSpeech2

RUN pip install -r requirements.txt && \
    unzip -qq hifigan/generator_universal.pth.tar.zip -d hifigan/ && \
    wget --content-disposition https://figshare.com/ndownloader/articles/19350539/versions/1 && \
    unzip -qq 19350539.zip && \
    mv yiddish_textgrids*.zip preprocessed_data/ && \
    unzip -qq preprocessed_data/yiddish_textgrids_yivo_respelled.zip && \
    unzip -qq preprocessed_data/yiddish_textgrids_yivo_original.zip && \
    unzip -qq preprocessed_data/yiddish_textgrids_hasidic.zip && \
    unzip -qq pretrained_models.zip && \
    pip install -q yiddish

ENTRYPOINT ["sh", "-c", "while true; do sleep infinity; done"]
```

**Comment by ibleaman** [comment]
Are you trying to replicate the Google Colab [demo](https://colab.research.google.com/drive/1xv0I_auaZ9rdNMMyrBpJHvOotH9w_BHa?usp=sharing) on your own server? Or did you find a bug in this `yiddish-tts-texts` repo?

If the first, maybe this will help. Inside the demo, click the "Show code" link on each cell to make sure you are replicating all of the necessary steps. One of them unzips the pretrained models and copies the `100000.pth.tar` files into the relevant output folders.
